language: cpp
dist: trusty
install:
    - cp cmake/wiringPi/CMakeLists.txt wiringPi/wiringPi && cp toolchain-rpi-c.cmake wiringPi/wiringPi
    - cd wiringPi/wiringPi/
    - cmake -DCMAKE_TOOLCHAIN_FILE=toolchain-rpi-c.cmake . && make -j$(nproc)
    - cd ../../
script:
    - cmake -DCMAKE_TOOLCHAIN_FILE=toolchain-rpi-cxx.cmake . && make -j$(nproc)


