language: cpp
dist: trusty
install:
    - cp cmake/wiringPi/CMakeLists.txt wiringPi/wiringPi
    - cd wiringPi/wiringPi/
    - cmake -DCMAKE_TOOLCHAIN_FILE=../../cmake/toolchain/toolchain-rpi-travis-c.cmake . && make -j$(nproc)
    - cd ../../
script:
    - cmake -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain/toolchain-rpi-travis-cxx.cmake . && make -j$(nproc)


