language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run -m unittest -v --omit '/home/travis/virtualenv*'
after_success:
    coveralls