language: cpp
dist: trusty
install:
    - cp cmake/wiringPi/CMakeLists.txt libs/wiringPi/wiringPi
    - cd libs/wiringPi/wiringPi/
    - cmake -DCMAKE_TOOLCHAIN_FILE=../../../cmake/toolchain/toolchain-rpi-travis-c.cmake . && make -j$(nproc)
    - cd ../../../
script:
    - cd poller-pi
    - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/toolchain-rpi-travis-cxx.cmake . && make -j$(nproc)
    - cd ..
    - cd ds-server
    - cmake . && make -j$(nproc)
    - cd ..
    - scripts/build_openssl.sh


